const pillarBackend = {
    latestBlock: 'latestBlock_zil',
    latestDsEpoch: 'latestDsEpoch_zil',
    latestMiniEpoch: 'latestMiniEpoch_epoch',
    lastConfirmedBlock: 'lastConfirmedBlock_zil',
    Binance: 'Binance',
    WARNINGCONSENT: `By checking the below box I understand that the Pillar Protocol code (https://viewblock.io/zilliqa/address/zil102wnukht6tkalgdc3v7fw3llhpu800ft943la8?tab=code,https://viewblock.io/zilliqa/address/zil13ls52yyyx68n6gvrpq24lwezgvrjdjh0ueehar?tab=code) and the current website has not been audited by a third party. I understand that by using such software, I run the risk of losing all my funds. I willingly take this risk to partake in the usage of the Pillar Protocol and I waive all rights if any loss results from me using the Pillar Protocol.`,
    events: {
        ProxyEvents: {
            RegisterCollateral: 'RegisterCollateral',
            PriceUpdated: 'PriceUpdated',
            SignatureValid: 'SignatureValid',
            RawDataToVerifySignature: 'RawDataToVerifySignature',
            TransferOwnership: 'TransferOwnership',
        },
        VaultFactoryEvents: {
            CreateNewVault: 'CreateNewVault',
            AddCollateral: 'AddCollateral',
            RecipientAcceptTransferFrom: 'RecipientAcceptTransferFrom',
            TransferFromSuccessCallBack: 'TransferFromSuccessCallBack',
            MintPillar: 'MintPillar',
            Repay: 'Repay',
            MintSuccessCallBack: 'MintSuccessCallBack',
            CollateralizationRatio: 'CollateralizationRatio',
            Liquidate: 'Liquidate',
            BurnFromSuccessCallBack: 'BurnFromSuccessCallBack',
            TransferSuccessCallBack: 'TransferSuccessCallBack',
            ReleaseCollateral: 'ReleaseCollateral',
            MarginalInterest: 'MarginalInterest',
        },
        StorageEvents: {
            Stat: 'Stat',
            TransferOwnership: 'TransferOwnership',
        },
        CollateralTokenEvents: {
            Minted: 'Minted',
            IncreasedAllowance: 'IncreasedAllowance',
            DecreasedAllowance: 'DecreasedAllowance',
            TransferSuccess: 'TransferSuccess',
            TransferFromSuccess: 'TransferFromSuccess',
            Burnt: 'Burnt',
        },
        PillarTokenEvents: {
            Minted: 'Minted',
            IncreasedAllowance: 'IncreasedAllowance',
            DecreasedAllowance: 'DecreasedAllowance',
            TransferSuccess: 'TransferSuccess',
            TransferFromSuccess: 'TransferFromSuccess',
            BurnFromSuccess: 'BurnFromSuccess',
            Burnt: 'Burnt',
            TransferOwnership: 'TransferOwnership',
        },
        StakingEvents: {
            LockedTokens: 'LockedTokens',
            ChangeDelegationContract: 'ChangeDelegationContract',
            RecipientAcceptTransferFrom: 'RecipientAcceptTransferFrom',
            TransferFromSuccessCallBack: 'TransferFromSuccessCallBack',
            NewUnlockRequest: 'NewUnlockRequest',
            DeleteUnlockRequest: 'DeleteUnlockRequest',
            WithdrawTokens: 'WithdrawTokens',
            TransferOwnership: 'TransferOwnership',
            TransferSuccessCallBack: 'TransferSuccessCallBack',
        },
        DelegateEvents: {
            UpdateDelegation: 'UpdateDelegation',
            UpdateVotes: 'UpdateVotes',
            TransferOwnership: 'TransferOwnership',
        },
        RewardEvents: { RewardTokenForEpoch: 'RewardTokenForEpoch', RecordReward: 'RecordReward', ClaimReward: 'ClaimReward' },
    },
};

module.exports = pillarBackend;
